name: Check Branch Name
on:
  pull_request:
   types: [opened, synchronize]

jobs:
  check-branch:
   runs-on: ubuntu-latest
    steps:
     name: Check branch name
     run: |
      if [[ "${{ github.head_ref }}" != "nombre-del-alumno" ]]; then
       echo "Error: Debes trabajar en la rama 'nombre-del-alumno'"
       exit 1
      fi
